/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defentthefort;


import BaseDeDatos.BDUsuarios;
import java.awt.Color;
import java.io.Serializable;
import javax.swing.JButton;
import javax.swing.JTextField;


public class GUIPartida extends javax.swing.JFrame implements Serializable{
    int SIZE = 30;
    Partida partida;
    BDUsuarios usuarios;
    
    public GUIPartida(String jugador, Partida partida) {
        initComponents();
        this.partida = partida;
        this.setTitle(jugador);
        pnlAreaJuego.setSize(1000, 1000);
        generarMatriz();
    }
    
    private void generarMatriz(){
       //Generar botones
       int posX = 0;
       int posY = 0;
       int contador = 1;
       //------------------------------------------
       for(int i = 0; i < 625; i++){
           JButton btn = new JButton("");
           if((contador%2) == 0){
               btn.setBackground(new Color(0,153,0));
               contador = 1;
           }
           else{
              btn.setBackground(new Color(0,102,0));
              contador += 1; 
           }          
           btn.setSize(SIZE, SIZE);
           //-------------------------------
           if(i%25 == 0 && i>0){
               posX = 0;
               posY += SIZE;
           }
           //------------------------------
           btn.setLocation((SIZE*posX++), posY);

           pnlAreaJuego.add(btn);
       }
    }



   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAreaJuego = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        pnlAreaJuego.setBackground(new java.awt.Color(153, 51, 0));

        javax.swing.GroupLayout pnlAreaJuegoLayout = new javax.swing.GroupLayout(pnlAreaJuego);
        pnlAreaJuego.setLayout(pnlAreaJuegoLayout);
        pnlAreaJuegoLayout.setHorizontalGroup(
            pnlAreaJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        pnlAreaJuegoLayout.setVerticalGroup(
            pnlAreaJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAreaJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAreaJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if (((int)evt.getKeyChar())==27){
            this.setVisible(false);
        }
    }//GEN-LAST:event_formKeyTyped

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlAreaJuego;
    // End of variables declaration//GEN-END:variables
}
