/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defentthefort;


import BaseDeDatos.BDUsuarios;
import java.awt.Color;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;


public class GUIPartida extends javax.swing.JFrame implements Serializable{
    int SIZE = 30;
    Partida partida;
    BDUsuarios usuarios;
    
    public GUIPartida(String jugador, Partida partida) {
        initComponents();
        this.partida = partida;
        this.setTitle("Defent The Fort: Zombie Attack \t"+jugador);
        pnlAreaJuego.setSize(1000, 1000);
        generarMatriz();
    }
    
    private void generarMatriz(){   //Generar botones
       int posX = 0;
       int posY = 0;
       //------------------------------------------
       for(int i = 0; i < 625; i++){
           JButton btn = new JButton("");
           if((i%2) == 0){
               btn.setBackground(new Color(0,153,0));
           }else{
              btn.setBackground(new Color(0,102,0));
           }          
           btn.setSize(SIZE, SIZE);
        //-------------------------------
           if(i%25 == 0 && i>0){
               posX = 0;
               posY += SIZE;
           }
        //------------------------------
           btn.setLocation((SIZE*posX++), posY);
           pnlAreaJuego.add(btn);
       }
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAreaJuego = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setPreferredSize(new java.awt.Dimension(1110, 750));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        pnlAreaJuego.setBackground(new java.awt.Color(77, 49, 36));

        jButton1.setBackground(new java.awt.Color(102, 255, 51));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAreaJuegoLayout = new javax.swing.GroupLayout(pnlAreaJuego);
        pnlAreaJuego.setLayout(pnlAreaJuegoLayout);
        pnlAreaJuegoLayout.setHorizontalGroup(
            pnlAreaJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaJuegoLayout.createSequentialGroup()
                .addContainerGap(1048, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        pnlAreaJuegoLayout.setVerticalGroup(
            pnlAreaJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreaJuegoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(795, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAreaJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAreaJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if (((int)evt.getKeyChar())==27){
            this.setVisible(false);
        }
    }//GEN-LAST:event_formKeyTyped
boolean encendido = true;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ImageIcon p = new ImageIcon("src\\Imagenes\\Arbol.png");
        
        if (encendido){
           jButton1.setIcon(p);
            System.out.println("Aparece");
       }else{
           jButton1.setIcon(null);
           System.out.println("Desaparece");
    }
        encendido = !encendido;
        validate();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel pnlAreaJuego;
    // End of variables declaration//GEN-END:variables
}
